// Measure the delivered colossus GLBs into the flight colliders the game registers before they load.
//   node asset-pipeline/colossi/meta.mjs
// Writes src/world/colossi/colossiMeta.ts: per model its height and, per height band, the solid cross-section as a
// few circles [x, z, r] (asset metres, node matrix applied, origin as authored). A band is rasterised by scanlines
// along x at three heights (solid by ray winding), then covered greedily: the uncovered cell deepest inside the
// solid takes a circle reaching the nearest empty cell, until every cell is within that circle or a fringe of it.
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { NodeIO } from '@gltf-transform/core'
import { ALL_EXTENSIONS } from '@gltf-transform/extensions'
import { MeshoptDecoder } from 'meshoptimizer'
import { Vector3 } from 'three'
import { nodeMesh, solidRuns } from '../lib/solid.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..', '..')
const dir = resolve(root, 'public', 'assets', 'colossi')
await MeshoptDecoder.ready
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ 'meshopt.decoder': MeshoptDecoder })

/** Band height and raster cell (asset metres) per model: the thin sword blade needs the finer cell. */
const MODELS = { guardian_a: { band: 7.5, cell: 2.5 }, guardian_b: { band: 7.5, cell: 2.5 }, giant_sword: { band: 10, cell: 2 } }
const RAY_HEIGHTS = [0.15, 0.5, 0.85]
/** A cell this many cells beyond a circle's edge counts as covered by it (at most that much of the rim is left out). */
const FRINGE = 0.75
const round = (v, d = 1) => Math.round(v * 10 ** d) / 10 ** d

function bandCover(mesh, box, lo, hi, cell) {
  const nx = Math.ceil((box.max.x - box.min.x) / cell) + 1, nz = Math.ceil((box.max.z - box.min.z) / cell) + 1
  const x0 = box.min.x - 1, solid = new Uint8Array(nx * nz), origin = new Vector3(), along = new Vector3(1, 0, 0)
  const cx = (i) => box.min.x + i * cell, cz = (j) => box.min.z + j * cell
  for (let j = 0; j < nz; j++) for (const f of RAY_HEIGHTS) {
    origin.set(x0, lo + (hi - lo) * f, cz(j))
    for (const [a, b] of solidRuns(mesh, origin, along)) for (let i = 0; i < nx; i++) if (cx(i) >= x0 + a && cx(i) <= x0 + b) solid[j * nx + i] = 1
  }
  const cells = []
  for (let j = 0; j < nz; j++) for (let i = 0; i < nx; i++) if (solid[j * nx + i]) cells.push([i, j])
  // Depth of each solid cell: distance to the nearest empty cell centre (outside the grid counts as empty).
  const depth = cells.map(([i, j]) => {
    let best = Math.min(i + 1, j + 1, nx - i, nz - j) * cell
    for (let jj = 0; jj < nz; jj++) for (let ii = 0; ii < nx; ii++) if (!solid[jj * nx + ii]) best = Math.min(best, Math.hypot(ii - i, jj - j) * cell)
    return best
  })
  const covered = new Uint8Array(cells.length), out = []
  for (;;) {
    let pick = -1
    for (let k = 0; k < cells.length; k++) if (!covered[k] && (pick < 0 || depth[k] > depth[pick])) pick = k
    if (pick < 0) break
    const [pi, pj] = cells[pick], r = depth[pick]
    cells.forEach(([i, j], k) => { if (Math.hypot(i - pi, j - pj) * cell <= r + FRINGE * cell) covered[k] = 1 })
    out.push([round(cx(pi)), round(cz(pj)), round(r)])
  }
  return { circles: out, cells: cells.length }
}

const data = {}
for (const [name, { band, cell }] of Object.entries(MODELS)) {
  const doc = await io.read(resolve(dir, `${name}.glb`))
  const node = doc.getRoot().listNodes().find((n) => n.getMesh())
  const { mesh } = nodeMesh(node), box = mesh.geometry.boundingBox, bands = []
  let circles = 0
  for (let lo = box.min.y; lo < box.max.y - 0.5; lo += band) {
    const hi = Math.min(box.max.y, lo + band), cover = bandCover(mesh, box, lo, hi, cell)
    if (cover.circles.length) bands.push([round(lo), round(hi), cover.circles])
    circles += cover.circles.length
  }
  data[name] = { height: round(box.max.y - box.min.y), bands }
  console.log(name, 'height', data[name].height, 'bands', bands.length, 'circles', circles, 'max per band', Math.max(...bands.map((b) => b[2].length)))
}

const banner = '// Generated by asset-pipeline/colossi/meta.mjs from public/assets/colossi; do not edit.\n'
writeFileSync(resolve(root, 'src', 'world', 'colossi', 'colossiMeta.ts'), `${banner}
export type ColossusModel = ${Object.keys(MODELS).map((k) => `'${k}'`).join(' | ')}

/** One colossus in asset metres, origin as authored (guardians stand on it, the sword's tip is at it). */
export interface ColossusMeta {
  height: number
  /** Height bands [from, to] with the band's solid cross-section as circles [x, z, r]. */
  bands: [number, number, [number, number, number][]][]
}

export const COLOSSUS_META: Record<ColossusModel, ColossusMeta> = ${JSON.stringify(data)}
`)
