// Bake references into the shipped mesh. Runtime skinning keeps the surface exact throughout the swim.
import fs from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { NodeIO } from '@gltf-transform/core'
import { ALL_EXTENSIONS } from '@gltf-transform/extensions'
import { MeshoptDecoder } from 'meshoptimizer'
import { Matrix4, Vector3 } from 'three'
await MeshoptDecoder.ready
const source = 'public/assets/colossi/kun.glb'
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ 'meshopt.decoder': MeshoptDecoder })
const doc = await io.read(source), root = doc.getRoot()
const bone = root.listNodes().find((n) => n.getName() === 'root')
const inverse = new Matrix4().fromArray(bone.getWorldMatrix()).invert()
const nodes = root.listNodes().filter((n) => n.getSkin() && n.getMesh())
const triangles = [], restTriangles = []
let meshIndex = 0
for (const node of nodes) {
  const skin = node.getSkin(), joints = skin.listJoints(), ibm = skin.getInverseBindMatrices()
  const transforms = joints.map((joint, i) => new Matrix4().fromArray(joint.getWorldMatrix()).multiply(new Matrix4().fromArray(ibm.getElement(i, []))))
  for (const prim of node.getMesh().listPrimitives()) {
    const pos = prim.getAttribute('POSITION'), si = prim.getAttribute('JOINTS_0'), sw = prim.getAttribute('WEIGHTS_0'), idx = prim.getIndices()
    const vertices = [], fins = []
    for (let i = 0; i < pos.getCount(); i++) {
      const p = new Vector3().fromArray(pos.getElement(i, [])), js = si.getElement(i, []), ws = sw.getElement(i, [])
      const out = new Vector3(); let fin = 0
      for (let k = 0; k < 4; k++) {
        out.addScaledVector(p.clone().applyMatrix4(transforms[js[k]]), ws[k])
        if (joints[js[k]].getName().startsWith('fin_')) fin += ws[k]
      }
      vertices.push(out.applyMatrix4(inverse)); fins.push(fin > 0.3)
    }
    for (let t = 0; t < idx.getCount() / 3; t++) {
      const ids = [idx.getScalar(t * 3), idx.getScalar(t * 3 + 1), idx.getScalar(t * 3 + 2)]
      const p = ids.map((i) => vertices[i]), c = p.reduce((s, v) => s.add(v), new Vector3()).multiplyScalar(1 / 3)
      if (ids.some((i) => fins[i]) || Math.abs(c.x) > 40 || c.z < -80 || c.z > 100 || c.y < 10) continue
      triangles.push(meshIndex, t); restTriangles.push(p)
    }
    meshIndex++
  }
}
if (restTriangles.length < 500) throw new Error('Deck selection unexpectedly small; check coordinate system')
const seeds = [[0, -45], [0, -25], [-20, 0], [-20, 20], [0, 45], [0, 65]]
const orbs = seeds.map(([x, z]) => {
  let best = null
  restTriangles.forEach(([a, b, c], triangle) => {
    const d = (b.z - c.z) * (a.x - c.x) + (c.x - b.x) * (a.z - c.z)
    if (Math.abs(d) < 1e-9) return
    const u = ((b.z - c.z) * (x - c.x) + (c.x - b.x) * (z - c.z)) / d
    const v = ((c.z - a.z) * (x - c.x) + (a.x - c.x) * (z - c.z)) / d
    if (u < 0 || v < 0 || u + v > 1) return
    const y = a.y * u + b.y * v + c.y * (1 - u - v)
    const normal = b.clone().sub(a).cross(c.clone().sub(a)).normalize()
    if (normal.y < Math.cos(40 * Math.PI / 180)) return
    if (!best || y > best.y) best = { triangle, u, v, x, y, z }
  })
  if (!best) throw new Error(`No safe orb anchor at ${x},${z}`)
  return best
})
const packed = Buffer.from(new Uint32Array(triangles).buffer).toString('base64')
const hash = createHash('sha256').update(await fs.readFile(source)).digest('hex')
await fs.writeFile('src/world/colossi/kunDeckMeta.ts', `// Generated by asset-pipeline/kun/deck.mjs; mesh SHA-256 ${hash}\nexport const KUN_DECK = ${JSON.stringify({ meshes: meshIndex, triangles: packed, orbs })} as const\n`)
console.log(JSON.stringify({ triangles: restTriangles.length, orbs }, null, 2))
