import { chromium } from 'playwright'
import fs from 'node:fs/promises'
import assert from 'node:assert/strict'

const browser = await chromium.launch({ headless: true,
  executablePath: process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  args: ['--use-angle=d3d11'],
})
const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 1 })
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
await fs.mkdir('artifacts/characters', { recursive: true })
const samples = []
const snapshot = () => page.evaluate(() => window.__playerSnapshot())
const phase = (value) => page.waitForFunction((p) => window.__playerSnapshot?.().phase === p, value, { timeout: 30000 })
async function capture(name) {
  const state = await snapshot()
  samples.push({ name, ...state })
  await page.screenshot({ path: `artifacts/characters/${name}.png` })
  console.log(name, state.phase, state.position, state.character, Object.keys(state.joints).length)
  return state
}
try {
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: /进入仙宗/ }).waitFor({ timeout: 180000 })
  await page.getByRole('button', { name: /进入仙宗/ }).click()
  await page.waitForTimeout(1200)
  const idle = await capture('male-idle')
  assert.ok(idle.bones && Object.keys(idle.joints).length >= 20, 'Skinned male rig must be mounted')
  await page.keyboard.down('w')
  await page.waitForTimeout(1000)
  const walk = await capture('male-walk')
  assert.ok(walk.position[2] < idle.position[2] - 2, 'Walking must move the character')
  assert.notDeepEqual(walk.joints, idle.joints, 'Bones must animate while walking')
  await page.keyboard.up('w')
  await page.keyboard.press('f')
  await phase('SUMMONING')
  await page.waitForTimeout(450)
  await capture('male-summon')
  await page.keyboard.press('2')
  assert.equal((await snapshot()).character, 'male', 'Switching must be blocked during summoning')
  await phase('BOARDING')
  await page.waitForTimeout(500)
  await capture('male-jump')
  await phase('FLIGHT')
  await capture('male-mounted')
  await page.keyboard.down('Space')
  await page.keyboard.down('w')
  await page.waitForTimeout(1800)
  await page.keyboard.up('w')
  await page.keyboard.up('Space')
  await page.waitForTimeout(600)
  const flying = await capture('male-flight')
  assert.ok(flying.position[1] > 10, 'Flight must gain altitude')
  await page.keyboard.down('Alt')
  await page.evaluate(() => {
    const event = new MouseEvent('mousemove', { bubbles: true, altKey: true })
    Object.defineProperty(event, 'movementX', { value: Math.PI / 2 / 0.0025 })
    window.dispatchEvent(event)
  })
  await page.waitForTimeout(1000)
  await capture('male-flight-side')
  await page.keyboard.up('Alt')
  await page.keyboard.press('2')
  await page.waitForFunction(() => window.__playerSnapshot?.().character === 'female' && window.__playerSnapshot?.().ready && Object.keys(window.__playerSnapshot().joints).length >= 20, null, { timeout: 180000 })
  await page.waitForTimeout(800)
  const female = await capture('female-flight')
  assert.equal(female.sword, 'Sword_female', 'Female must use her own sword')
  assert.ok(Math.abs(female.position[1] - flying.position[1]) < 2, 'Switching must preserve flight altitude')
  await page.keyboard.press('f')
  await phase('LANDING')
  await capture('female-landing')
  await phase('GROUND')
  await capture('female-ground')
  await page.keyboard.press('f')
  await phase('SUMMONING')
  await page.waitForTimeout(500)
  await capture('female-summon')
  await page.evaluate(() => document.exitPointerLock())
  await page.waitForTimeout(150)
  const paused = await snapshot()
  await page.waitForTimeout(600)
  assert.equal((await snapshot()).elapsed, paused.elapsed, 'Releasing the mouse must pause the summon sequence')
  await page.locator('.resume-button').click()
  await phase('BOARDING')
  await page.waitForTimeout(500)
  await capture('female-jump')
  await phase('FLIGHT')
  await capture('female-mounted')
  await page.keyboard.down('Alt')
  await page.evaluate(() => {
    const event = new MouseEvent('mousemove', { bubbles: true, altKey: true })
    Object.defineProperty(event, 'movementX', { value: Math.PI / 2 / 0.0025 })
    window.dispatchEvent(event)
  })
  await page.waitForTimeout(1000)
  await capture('female-flight-side')
  await page.keyboard.up('Alt')
  await page.keyboard.press('f')
  await phase('GROUND')
  await page.keyboard.press('1')
  await page.waitForTimeout(800)
  assert.equal((await snapshot()).character, 'male')
  await capture('male-return')
  const boundaryChecks = await page.evaluate(async () => {
    const { createPlayerRuntime, requestFlightToggle, stepPlayer } = await import('/src/world/player/playerMotion.ts')
    const state = createPlayerRuntime()
    const unloaded = requestFlightToggle(state)
    state.ready = true
    state.position.set(0, 24, -172.99)
    const wall = requestFlightToggle(state)
    const wallPhase = state.phase
    const wallDestination = state.destination.toArray()
    state.phase = 'FLIGHT'
    state.position.set(500, 80, 100)
    const unsafeLanding = requestFlightToggle(state)
    const unsafePhase = state.phase
    state.position.set(0, 80, 100)
    requestFlightToggle(state)
    const landingPhase = state.phase
    requestFlightToggle(state)
    const cancelledPhase = state.phase
    state.position.set(0, 0.55, 100)
    state.velocity.set(0, -10, 0)
    stepPlayer(state, state.position.clone().set(0, -1, 0), false, 1 / 60)
    return { unloaded, wall, wallPhase, wallDestination, unsafeLanding, unsafePhase, landingPhase, cancelledPhase, minHeight: state.position.y }
  })
  assert.ok(boundaryChecks.unloaded)
  assert.equal(boundaryChecks.wall, null)
  assert.equal(boundaryChecks.wallPhase, 'SUMMONING')
  assert.ok(Math.abs(boundaryChecks.wallDestination[0]) > 1, 'Wall summon must find a clear side')
  assert.ok(boundaryChecks.unsafeLanding)
  assert.equal(boundaryChecks.unsafePhase, 'FLIGHT')
  assert.equal(boundaryChecks.landingPhase, 'LANDING')
  assert.equal(boundaryChecks.cancelledPhase, 'FLIGHT')
  assert.equal(boundaryChecks.minHeight, 0.55)
  console.log('Boundary checks passed', boundaryChecks)
  assert.deepEqual(errors, [], 'Browser must have no errors')
} finally {
  await fs.writeFile('artifacts/characters/report.json', JSON.stringify({ samples, errors }, null, 2))
  await browser.close()
}
